// Load in our dependencies
#include <exception>
#include <iostream>
using namespace std;

int main (){
  throw runtime_error {"Test error"};
}
